name: Laravel

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  laravel-tests:
    
    runs-on: ubuntu-latest
  
    container:
      image: kirschbaumdevelopment/laravel-test-runner:7.4
    
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
    steps:
      - uses: actions/checkout@v2
      - name: Install composer dependencies
        run: |
          composer install --no-scripts
      - name: Copy .env.ci to .env
        run: |
          cp .env.ci .env
      - name: Generate Key
        run: |
          php artisan key:generate
      - name: Directory Permissions
        run: |
          chmod -R 777 storage bootstrap/cache
      - name: Symlink Storage
        run: |
          php artisan storage:link
      - name: Install front-end dependencies
        run: |
          npm install
          npm run dev
      - name: Run Testsuite
        run: vendor/bin/phpunit tests/
