name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:
    
    runs-on: ubuntu-latest
  
    container:
      image: kirschbaumdevelopment/laravel-test-runner:7.4
    
    steps:
      - uses: actions/checkout@v2
      - name: Install composer dependencies
        run: |
          composer install --no-scripts
      - name: Copy .env.example to .env
        run: |
          cp .env.example .env
      - name: Generate Key
        run: |
          php artisan key:generate
      - name: Directory Permissions
        run: |
          chmod -R 777 storage bootstrap/cache
      - name: Symlink Storage
        run: |
          php artisan storage:link
      - name: Install front-end dependencies
        run: |
          npm install
          npm run dev
      - name: Create Database
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Run Testsuite
        run: vendor/bin/phpunit
      - name: Check the duplicate code in app directory
        run: ./vendor/bin/phpcpd app/ --min-lines=5 --min-tokens=10
