name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:
    
    runs-on: ubuntu-latest
  
    container:
      image: kirschbaumdevelopment/laravel-test-runner:7.4
    
    env:
      DB_DATABASE: test
      DB_USER: root
      DB_PASSWORD: password
    
    steps:
      - uses: actions/checkout@v2
      - name: Install composer dependencies
        run: |
          composer install --no-scripts
      - name: Copy .env.ci to .env
        run: |
          cp .env.ci .env
      - name: Set Up MySQL
        run: |
          sudo /etc/init.d/mysql start
      - name: Generate Key
        run: |
          php artisan key:generate
      - name: Directory Permissions
        run: |
          chmod -R 777 storage bootstrap/cache
      - name: Symlink Storage
        run: |
          php artisan storage:link
      - name: Install front-end dependencies
        run: |
          npm install
          npm run dev
      - name: Run Testsuite
        run: vendor/bin/phpunit
      - name: Check the duplicate code in app directory
        run: ./vendor/bin/phpcpd app/ --min-lines=5 --min-tokens=10
