name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:
    
    runs-on: ubuntu-latest
  
    container:
      image: kirschbaumdevelopment/laravel-test-runner:7.4
    
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          # The hostname used to communicate with the PostgreSQL service container
          POSTGRES_HOST: postgres
          # The default PostgreSQL port
          POSTGRES_PORT: 5432
          POSTGRES_DB: test
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - uses: actions/checkout@v2
      - name: Install composer dependencies
        run: |
          composer install --no-scripts
      - name: Copy .env.ci to .env
        run: |
          cp .env.ci .env
      - name: Generate Key
        run: |
          php artisan key:generate
      - name: Directory Permissions
        run: |
          chmod -R 777 storage bootstrap/cache
      - name: Symlink Storage
        run: |
          php artisan storage:link
      - name: Install front-end dependencies
        run: |
          npm install
          npm run dev
      - name: Database Migrate
        run: |
          php artisan migrate:fresh --seed
      - name: Run Testsuite
        run: vendor/bin/phpunit
      - name: Check the duplicate code in app directory
        run: ./vendor/bin/phpcpd app/ --min-lines=5 --min-tokens=10
